name: Build Electron

on:
  push:
    tags:
      - pe-*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      UAT_REPO_NAME: uat-picencrypt
      PUBLIC_URL: ./

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          build_script_name: build:electron

          # If the commit is tagged with a version (e.g. "pe-3.9.20"),
          # release the app after building. Should always be true.
          release: ${{ startsWith(github.ref, 'refs/tags/pe-') }}
